### ISSUE TITLE
Pinning reminder only shows up for participant/client (not host/therapist) 

### ISSUE THREAD

**Issue by dabbish** [CoExLab/pinmi#84] opened 2024-02-06 22:40 UTC
Pinning reminder (Pin at least once) only shows up for participant/client (not host/therapist)

**Comment by dabbish** [comment] 2024-03-12 21:21
@torqueJY32 can you check this one out? We are thinking you might know an easy fix / why its happening

**Comment by torqueJY32** [comment] 2024-03-12 21:33
resolved in the latest push -- host was intended not to have the reminder for some reason

**Closed by torqueJY32** 2024-03-12 21:33 UTC
